### ISSUE TITLE
메인_중단 이미지 배너 텍스트 수정 외

### ISSUE THREAD

**Issue by xeno-xeno** [codenamu/2015-transparency#7]
가. 메인> 중단 - 사이트 설명을 위한 배너 텍스트 수정 

> [업데이트 내용]
> 내가 낸 세금 꼭 필요한 곳에 잘 사용되고 있을까요?
> 
> “월급 받을 때 세금 내는데 어떻게 쓰이고 있을까?"
> “내가 세금을 얼마나 내었고, 정부는 나에게 무엇을 해 준걸까?"
> “연말정산은 뭔데 내가 세금을 더 내야하지?"
> 
> 모두들 한번쯤 생각해보신적 있지 않나요?
> 
> ‘지켜보고 있다 대한민국 재정’ 프로젝트는 공개된 정부의 재정 정보를 꼼꼼히 살펴보고, 
> 어려운 재정정보의 이해를 돕고 재정 데이터를 보다 쉽게 활용할 수 있도록 
> row data 아카이빙, 데이터 분석, 시각화 등을 합니다. 
> 
> -프로젝트 소개 ( 링크) 

나. 홈 > 소개 페이지 원고 업데이트 반영
https://docs.google.com/document/d/14x9x5uaWl8QDIhDl9zxI02U379VHmZCdkktEolFqZX4/edit#heading=h.pn6hgwsgrs7o

**Comment by mozodev** [comment]
가)는 #3 에서 해결~
